language : cpp
compiler : clang
before_install :
script: 
 - sudo apt-get install libgtest-dev
 - sudo apt-get install cmake
 - cd /usr/src/gtest 
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd -
after_success:
 - cmake CMakeLists.txt
 - make
 - ./runTests
